Add sort key option for ImageViewer
glotzerlab/signac-dashboard pull request #155
Opened 2022-10-25 15:59 UTC by Charlottez112

Add an option for specifying the order of figures. Currently the `ImageViewer` would display figures in a random order. This feature can also be added to other modules such as `VideoViewer`

## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac-dashboard/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac-dashboard/blob/master/ContributorAgreement.md).
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] The [package documentation](https://github.com/glotzerlab/signac-dashboard/tree/master/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-dashboard/blob/master/changelog.txt) and added any related issue and pull request numbers for future reference.

2022-10-26 15:04 UTC, cbkerr requested changes
Nice!

Could you please:
- add docstring about this
- remove the code associated with your other PR

One consideration: should different file types be grouped together? What should the default be?

Sorting alphabetically could result in mixing of file types. Does this matter?
image_a.png
image_b.gif
image_b.png

2022-10-26 22:37 UTC, bdice commented
> One consideration: should different file types be grouped together? What should the default be?
> Sorting alphabetically could result in mixing of file types. Does this matter?
> image_a.png
> image_b.gif
> image_b.png

The sort function should act on the file path relative to the job directory. The caller should be responsible for grouping the results by extension in the sort function, if that is desired.

2022-11-16 23:08 UTC, Charlottez112 commented
> > One consideration: should different file types be grouped together? What should the default be?
> > Sorting alphabetically could result in mixing of file types. Does this matter?
> > image_a.png
> > image_b.gif
> > image_b.png
> 
> The sort function should act on the file path relative to the job directory. The caller should be responsible for grouping the results by extension in the sort function, if that is desired.

So I guess the only thing left is to add docstring?

2022-11-17 18:09 UTC, cbkerr commented
I added the same option to VideoViewer which also deals with files.

> docstring

What do you think of how I described the argument in the `video_viewer` module?

2022-11-18 15:58 UTC, Charlottez112 commented
> I added the same option to VideoViewer which also deals with files.
> 
> > docstring
> 
> What do you think of how I described the argument in the `video_viewer` module?

I think the name of the parameter is self-explanatory, so probably don't need to mention it's passed internally to `sorted`. But if you want to be more specific, we could probably be more direct and just say that it is the `key` parameter of `sorted`.

2022-11-30 17:27 UTC, bdice commented on signac_dashboard/modules/video_viewer.py
> +        self.sort_key = sort_key
Maybe sort these assignments to match the argument order in `__init__`.

2022-11-30 17:27 UTC, bdice commented on signac_dashboard/modules/image_viewer.py
> +        sort_key=None,
Add to the docstring above (copy from `VideoViewer`).

2023-03-24 00:27 UTC, b-butler approved these changes

2023-03-30 14:29 UTC, merged